name: Check Docker Version

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t shayhot/nodejs-app:latest .

      - name: Tag Docker Image
        run: docker tag shayhot/nodejs-app:latest shayhot/nodejs-app:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push shayhot/nodejs-app:latest
          docker push shayhot/nodejs-app:${{ github.run_number }}

      - name: Run Docker Container
        run: docker run -d --name nodejs-app -p 3000:3000 shayhot/nodejs-app:latest

        



