name: Node.js CI Workflow

on: 
  push:
    branches:
      - master  # Ensure this branch exists in your repo

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          repository: 'Shay-Hotoveli/Nodejs'  # Updated repo name
          ref: 'master'  # Change this if your branch is different

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies with npm
        run: npm install  

      - name: Run build
        run: npm run build  

      - name: Run tests
        run: npm test  

