# name: Node.js CI Workflow

# on: 
#   push:
#     branches:
#       - main  

# jobs:
#   checkout-code:
#     runs-on: ubuntu-latest  
#     steps:
#       - name: Checkout code from repo
#         uses: actions/checkout@v4
#         with:
#           repository: 'Shay-Hotoveli/Nodejs'
#           ref: 'main'

#   install-dependencies:
#     runs-on: ubuntu-latest  
#     needs: checkout-code  # Ensures checkout happens before this
#     steps:
#       - name: Checkout code from repo
#         uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Install dependencies
#         run: npm install  

#   build-project:
#     runs-on: ubuntu-latest  
#     needs: install-dependencies  # Ensures dependencies are installed before this
#     steps:
#       - name: Checkout code from repo
#         uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Install dependencies
#         run: npm install  
#       - name: Build the project
#         run: npm run build || echo 'Build command not defined yet!'

#   run-tests:
#     runs-on: ubuntu-latest  
#     needs: build-project  # Ensures build happens before this
#     steps:
#       - name: Checkout code from repo
#         uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Install dependencies
#         run: npm install  
#       - name: Run tests (Temporary Fix)
#         run: npm run test || echo 'No tests configured yet!'

name: Check Docker Version
on: push
jobs:
  check-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker Version
        run: docker --version


